version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build phase
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 323581685419.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t duenohfao/capstone-proj .
      - docker tag duenohfao/capstone-proj:latest 323581685419.dkr.ecr.ap-southeast-1.amazonaws.com/duenohfao/capstone-proj:latest
      # - python app.py

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 323581685419.dkr.ecr.ap-southeast-1.amazonaws.com/duenohfao/capstone-proj:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes